services:
  - type: web
    name: hepatitis-dashboard
    env: docker
    region: oregon
    plan: free
    dockerfilePath: docker/Dockerfile.frontend
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_RUNONSAVE
        value: false
