services:
  - type: web
    name: hepatitis-dashboard
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/hepatitis_dashboard.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_RUNONSAVE
        value: false
